version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: daily_anki_postgres_clone
    restart: always
    ports:
      - '5441:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: anki_nestjs_clone
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
